"use client";

console.warn(
  "⚠️ Avoid importing components from 'index.js' for better performance. This practice is deprecated and may be removed in the future."
);

export * as _Builtin from "./_Builtin";
export * from "./devlinkContext";
export * from "./interactions";
export * from "./utils";
export * from "./devlink";
export * from "./Argument";
export * from "./AvisGoogle";
export * from "./Banner";
export * from "./BannerImgLeftGreenShadow";
export * from "./BannerImgLeftGreyShadow";
export * from "./BannerImgRight";
export * from "./BannerTextOnly";
export * from "./CardAtouts";
export * from "./CardKeyPoints3C";
export * from "./CardKeyPoints4C";
export * from "./CardOfferPrimary";
export * from "./CarteDesSalles";
export * from "./Checklist";
export * from "./ChecklistDisable";
export * from "./ChecklistItem";
export * from "./ChecklistItemSmall";
export * from "./ChecklistItemSmallMedium";
export * from "./Chips";
export * from "./ClubsCard";
export * from "./ClubsCardLight";
export * from "./CoachCard";
export * from "./CoachingOptions";
export * from "./DevLinkProvider";
export * from "./DowloadAppArgument";
export * from "./DownloadApp";
export * from "./Faq";
export * from "./FaqFullWidth";
export * from "./FaqQA";
export * from "./Footer";
export * from "./FormLeadLp";
export * from "./Formulaire";
export * from "./FullWidthCover";
export * from "./FullWidthGreenXl";
export * from "./FullWidthPrimary";
export * from "./Header";
export * from "./ImageToContent";
export * from "./ImageToContentEnlighted";
export * from "./KeyPoint";
export * from "./LessonsCard";
export * from "./LessonsCardDetailed";
export * from "./LessonsCardLarge";
export * from "./LessonsSlider";
export * from "./NosAtouts";
export * from "./OfferCardDetailedMedium";
export * from "./OfferCardDetailedPrimary";
export * from "./OptionCardMediumColor";
export * from "./OptionCardPrimary";
export * from "./Popup";
export * from "./PopupClubGroup";
export * from "./PopupOverlay";
export * from "./PopupScript";
export * from "./PostsBannerListing";
export * from "./PostsCard";
export * from "./PostsCardFeatured";
export * from "./PostsSlider";
export * from "./RichText";
export * from "./Separator";
export * from "./SeparatorWave";
export * from "./SpacesCard";
export * from "./SpecialOffer";
export * from "./TestimoniesSlider";
export * from "./TexteSeo";
export * from "./Title3CardsCenter";
export * from "./TitleTextButton";
